[package]
name = "trae-shooting"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.17"
winit = "0.28"
env_logger = "0.10"
log = "0.4"
bytemuck = "1.4"
glam = "0.24"
image = "0.24"
anyhow = "1.0"
gilrs = "0.10"  # Xbox controller support
pollster = "0.3"